from models.model1 import Model1
from models.model2 import Model2
from models.model3 import Model3
from models.model4 import Model4
from models.model5 import Model5
from models.model6 import Model6
from models.model7 import Model7
from models.model8 import Model8
from models.model9 import Model9
from models.model10 import Model10
from models.model11 import Model11
from models.model12 import Model12
from models.model13 import Model13
from models.model14 import Model14
from models.model15 import Model15
from models.model16 import Model16
from models.model17 import Model17
from models.model18 import Model18
from models.model19 import Model19
from models.model20 import Model20